base: 50
growth_rate: 1.2
points_range:
  - 1
  - 5
message_cooldown: 30
alert_channel: ~ # will alert in DM by default but can be set to a channel ID
keys:
  levelup_message: "you have leveled up to level {level}!"
  levelup_message_dm: "you have leveled up to level {level} in {guild}!"
  roleup_message: "you have earned the role {role} for getting to level {level}!"
  roleup_message_dm: "you have earned the role {role} in {guild} for getting level {level}!"